export interface Order {
  id: string
  reference: string
  brandName: string
  retailerName: string
  status: string
  total: number
  currency: string
  itemCount: number
  createdAt: string
}

export interface OrderStatus {
  value: string
  label: string
  color: string
}

// --- Design Token types (generated by npm run sync-ds) ---

export interface ColorToken {
  name: string
  group: 'foundation' | 'neutral' | 'functional' | 'special'
  cssVar: string
  cssValue: string
  tailwindHex: string
}

export interface SpacingToken {
  name: string
  cssVar: string
  value: string
  px: number
}

export interface TypographyToken {
  name: string
  cssVar: string
  size: string
  sizePx: number
  lineHeight: string
  lineHeightPx: number
}

export interface RadiusToken {
  name: string
  cssVar: string
  value: string
  valuePx: number
}

export interface DesignTokens {
  version: string
  syncDate: string
  colors: ColorToken[]
  spacing: SpacingToken[]
  typography: TypographyToken[]
  radius: RadiusToken[]
}
