export interface Order {
  id: string
  reference: string
  brandName: string
  retailerName: string
  status: string
  total: number
  currency: string
  itemCount: number
  createdAt: string
}

export interface OrderStatus {
  value: string
  label: string
  color: string
}

// --- Factoring types ---

export interface FactoringBuyer {
  name: string
  siren: string
  city: string
  address: string
  contactName: string
  contactEmail: string
}

export interface FactoringDocument {
  name: string
  type: 'proforma' | 'invoice' | 'pod'
  size: string
}

export interface FactoringLoanRequest {
  id: string
  reference: string
  buyer: FactoringBuyer
  orderValue: number
  eligibleFor: string
  youReceive: number
  feePercent: number
  status: 'pending' | 'in-review' | 'approved' | 'funded' | 'refused'
  startedDate: string
  submittedDate?: string
  approvedDate?: string
  documents: FactoringDocument[]
}

export interface FactoringDashboardStats {
  totalAdvanced: number
  requestsSubmitted: number
  actionNeeded: number
}

// --- Design Token types (generated by npm run sync-ds) ---

export interface ColorToken {
  name: string
  group: 'foundation' | 'neutral' | 'functional' | 'special'
  cssVar: string
  cssValue: string
  tailwindHex: string
}

export interface SpacingToken {
  name: string
  cssVar: string
  value: string
  px: number
}

export interface TypographyToken {
  name: string
  cssVar: string
  size: string
  sizePx: number
  lineHeight: string
  lineHeightPx: number
}

export interface RadiusToken {
  name: string
  cssVar: string
  value: string
  valuePx: number
}

export interface DesignTokens {
  version: string
  syncDate: string
  colors: ColorToken[]
  spacing: SpacingToken[]
  typography: TypographyToken[]
  radius: RadiusToken[]
}
